package uk.gov.justice.laa_civil_manage_api.controllers;

import java.util.List;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ExpertController {
   
    @GetMapping("/expertTypes")
 
    public List<String> getExpertTypes() {
        return List.of(
            
            "A & E Consultant",
      "Aboriculturist",
      "Accountant",
      "Accountant Manager",
      "Accountant Partner",
      "Accountant Staff",
      "Accident Reconstruction",
      "Actuary",
      "Agricultural Expert",
      "Anaesthetist",
      "Arbitrator's fees",
      "Architect",
      "Benefits Expert",
      "Cardiologist",
      "Cell telephone site analysis",
      "Child Psychiatrist",
      "Child Psychologist",
      "Computer expert",
      "Consultant engineer",
      "Computer Consultant",
      "Assessment of supervised contact.",
      "Conveyancing expert",
      "Costs Draughtsman Fees",
      "Court of protection expert",
      "Dentist",
      "Dermatologist",
      "Disability consultant",
      "Diving Expert",
      "DNA (per person) – preparation of report",
      "DNA (per person) – testing of sample",
      "Doctor (General Practitioner)",
      "Employment consultant",
      "Consultant Engineer",
      "Enquiry agent",
      "Ear Nose and Throat Surgeon",
      "ENT surgeon",
      "Independent Environmental Health Officer",
      "Equine Expert",
      "Ergonomist",
      "Expert - Other",
      "Financial Adviser",
      "Fire assessor/explosives expert",
      "Forensic expert",
      "Geneticist",
      "General surgeon",
      "GP (records report)",
      "Gymnastics Expert",
      "Gynaecologist",
      "Health and Safety Officer",
      "Haematologist",
      "Handwriting expert",
      "Interpreter",
      "International Lawyer",
      "Lip reader / Signer",
      "Medical consultant",
      "Mediators Fees",
      "Medical records",
      "Meteorologist",
      "Medical Microbiologist",
      "Midwife",
      "Mining Consultant",
      "Musicologist",
      "Neonatologist (clin neg cerebral palsy)",
      "Neonatologist",
      "Neonatologist (non-clin neg cerebral palsy)",
      "Neuroradiologist (clin neg cerebral palsy)",
      "Neuroradiologist (non-clin neg cerebral palsy)",
      "Neurologist (clin neg cerebral palsy)",
      "Neurologist (non-clin neg cerebral palsy)",
      "Neuroradiologist",
      "Neurologist",
      "Neuropsychiatrist",
      "Neurosurgeon",
      "Nursing Expert",
      "Obstetrician",
      "Occupational Therapist",
      "Oncologist",
      "Ophthalmologist",
      "Orthopaedic Surgeon",
      "Osteopath",
      "Paediatrician",
      "Parental Assessment",
      "Pathologist",
      "Physical Education Expert",
      "Pharmacologist",
      "Photographer",
      "Physiotherapist",
      "Plastic Surgeon",
      "Process server",
      "Psychiatrist",
      "Psychotherapist",
      "Psychologist",
      "Radiologist",
      "Rheumatologist",
      "Risk assessment expert",
      "Independent social worker",
      "Sol(Higher Rights)Advoc for another firm",
      "Sol(Higher Rights) Advocacy for own firm",
      "Solicitor (Higher Rights) Opinion",
      "Site visit by an expert",
      "Speech Therapist",
      "Surgeon",
      "Surveyor (Housing Disrepair)",
      "Surveyor (Non-Housing Disrepair)",
      "Surveyor",
      "Telecommunications Expert",
      "Toxicologist",
      "Translator",
      "Trichologist",
      "Urologist",
      "Valuer",
      "Vet",
      "Voice recognition expert"
        );
    }
        
}
