version: '3.8'
services:
  mock-datastore:
    image: mockoon/cli:latest
    ports:
      - "3000:3000"
    volumes:
      # Mounts your local config file into the container
      - ./src/test/resources/mock-env.json:/data/mock-env.json
    command: ["--data", "/data/mock-env.json", "--port", "3000"]