[tools]
gradle = "9.3.1"
java = "25"
lefthook = "latest"

[tasks.build]
description = "Full project build"
run = "./gradlew build"

[tasks.dev]
description = "Run app in dev mode"
run = "./gradlew bootRun"

[tasks.test]
description = "Run unit tests"
run = "./gradlew test"

[tasks.coverage]
description = "Run tests and generate JaCoCo coverage report"
run = "./gradlew test jacocoTestReport"

[tasks.format]
description = "Format and check code using Spotless"
run = "./gradlew spotlessApply spotlessCheck"

[tasks.apidocs]
description = "Generate OpenAPI Schema from controllers"
run = "./gradlew generateOpenApiDocs"

[tasks.zap]
description = "Run Zap security scanning"
run = "./deploy/scripts/zap/zap-run-local.sh"

[tasks.check-deps]
description = "Check for outdated dependencies"
run = "./gradlew dependencyUpdates"