package uk.gov.justice.laa_civil_manage_api.models;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The type of document being uploaded as supporting evidence.")
public enum PriorAuthorityDocumentType {
  GATEWAY_EVIDENCE,
  MERITS_REPORT,
  STATEMENT_OF_CASE,
  COURT_APPLICATION,
  COURT_ORDER,
  EXPERT_REPORT,
  COURT_APPLICATION_OR_ORDER,
  PARENTAL_RESPONSIBILITY,
  LOCAL_AUTHORITY_ASSESSMENT,
  GROUNDS_OF_APPEAL,
  COUNSEL_OPINION,
  JUDGEMENT,
  PLF_COURT_ORDER,
  LETTER_OF_INSTRUCTION,
  ESTIMATE_OF_COSTS,
  ALTERNATIVE_QUOTE,
  OTHER_PARTY_CERTIFICATE_REFERENCE,
  OTHER_SUPPORTING_DOCUMENT,
  PRIMARY_QUOTE,
  ADDITIONAL_QUOTE
}
