spring:
  config:
    import: "optional:file:.env[.properties]"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/8352c342-da15-413a-8b5b-d89545766f0c/v2.0
          jwk-set-uri: https://login.microsoftonline.com/8352c342-da15-413a-8b5b-d89545766f0c/discovery/v2.0/keys
          audiences:
            - efb49b90-5365-456f-bc87-c5a613e0d08d
            - 024c9bb4-b5fd-434b-abff-1d7d7c8776f4
      client:
        registration:
          entra-obo-access-data-store:
            client-id: 024c9bb4-b5fd-434b-abff-1d7d7c8776f4
            scope:
              - api://devlexternal.onmicrosoft.com/efb49b90-5365-456f-bc87-c5a613e0d08d/access_as_user
        provider:
          azure-entra:
            token-uri: https://login.microsoftonline.com/8352c342-da15-413a-8b5b-d89545766f0c/oauth2/v2.0/token

custom:
  proxy:
    host: ""
    port: 0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: INFO
  structured:
    format:
      console: ""
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{correlationId:-},%X{traceId:-},%X{spanId:-}]){yellow} %clr(%-35logger{35}){cyan} : %m%n"

laa-civil-manage-api:
  access-data-store:
    operation-base-urls:
      get-applications: https://dev-token-enabled-laa-data-access-api-uat.cloud-platform.service.justice.gov.uk
      get-application-by-id: https://dev-token-enabled-laa-data-access-api-uat.cloud-platform.service.justice.gov.uk