spring:
  application:
    name: laa-civil-manage-api

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
        health: "actuator/health"
      exposure:
        include: "health,info,prometheus"

laa-civil-manage-api:
  data-store-url: ${MOCK_API_URL:http://127.0.0.1:3000}