spring:
  application:
    name: laa-civil-manage-api

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
        health: "actuator/health"
      exposure:
        include: "health,info,prometheus"

laa-civil-manage-api:
  data-store-config:
    url: "http://localhost:3000"