services:
  civil-manage:
    build: ../../../.
    ports:
      - "3000:3000"

  zap-scan:
    image: zaproxy/zap-stable@sha256:7c2f8afc893e4e4000be8ad3fd22013fc36e5cce59359349f5a2d45626e2ccb9
    command: zap.sh -cmd -port 9090 -autorun /zap/wrk/zap.yaml
    volumes:
      - ../../../.:/zap/wrk:rw
    links:
      - civil-manage