apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-civil-manage-api.fullname" . }}
  labels:
    {{- include "laa-civil-manage-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-civil-manage-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-civil-manage-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laa-civil-manage-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: SKIP_AUTH
              value: {{ .Values.env.skipAuth | default "false" | quote }}
            - name: AZURE_ENTRA_TENANT_ID
              value: {{ .Values.env.azureEntraTenantId | quote }}
            - name: AZURE_ENTRA_API_CLIENT_ID
              value: {{ .Values.env.azureEntraApiClientId | quote }}
            - name: ACCESS_DATA_STORE_BASE_URL
              value: {{ .Values.env.accessDataStoreBaseUrl | quote }}
            - name: AZURE_ENTRA_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-entra-api-client-secret
                  key: azure-entra-api-client-secret
            - name: AZURE_ENTRA_API_AUDIENCE
              value: {{ .Values.env.azureEntraApiAudience | quote }}
            - name: ACCESS_DATA_STORE_OBO_SCOPE
              value: {{ .Values.env.accessDataStoreOboScope | quote }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
