name: Build and Push Image
description: Build Image and Push to a Container Registry (with caching)
inputs:
  image_registry:
    required: false
    description: "Image Registry URL"
  image_repo:
    required: true
    description: "Image Repository URL"
  dockerfile_path:
    required: true
    description: "Dockerfile Path"
    default: "Dockerfile"
  image_tag:
    required: true
    description: "Image Tag"
    default: ${{ github.sha }}
  push_image:
    required: false
    description: "Whether to push the image to the registry"
    default: "true"
  additional_tag:
    required: false
    description: "Optional additional tag to apply to the image (e.g. 'main')"
    default: ""

outputs:
  image_registry:
    description: "Image Registry URL"
    value: ${{ steps.output.outputs.image_registry }}
  image_repo:
    description: "Image Repo Path"
    value: ${{ steps.output.outputs.image_repo }}
  image_tag:
    description: "Image Tag"
    value: ${{ steps.output.outputs.image_tag }}
  image_uri:
    description: "Image URI"
    value: ${{ steps.output.outputs.image_uri }}

runs:
  using: "composite"
  steps:
    - name: Docker Build (optionally push) with Cache
      id: build_and_push
      run: |
        IMAGE_NAME="${{ inputs.image_repo }}"
        if [[ -n "${{ inputs.image_registry }}" ]]; then
          IMAGE_NAME="${{ inputs.image_registry }}/${{ inputs.image_repo }}"
        fi

        ADDITIONAL_TAG_ARG=""
        if [[ -n "${{ inputs.additional_tag }}" ]]; then
          ADDITIONAL_TAG_ARG="-t ${IMAGE_NAME}:${{ inputs.additional_tag }}"
        fi
        if [[ "${{ inputs.push_image }}" == "true" ]]; then
          docker buildx build \
            --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t ${IMAGE_NAME}:${{ inputs.image_tag }} \
            $ADDITIONAL_TAG_ARG \
            -f ${{ inputs.dockerfile_path }} .
        else
          docker buildx build \
            --load \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t ${IMAGE_NAME}:${{ inputs.image_tag }} \
            $ADDITIONAL_TAG_ARG \
            -f ${{ inputs.dockerfile_path }} .
        fi

      shell: bash

    - name: Output
      id: output
      run: |
        IMAGE_NAME="${{ inputs.image_repo }}"
        if [[ -n "${{ inputs.image_registry }}" ]]; then
          IMAGE_NAME="${{ inputs.image_registry }}/${{ inputs.image_repo }}"
        fi

        echo image_registry=${{ inputs.image_registry }} >> "$GITHUB_OUTPUT"
        echo image_repo=${{ inputs.image_repo }} >> "$GITHUB_OUTPUT"
        echo image_tag=${{ inputs.image_tag }} >> "$GITHUB_OUTPUT"
        echo image_uri="${IMAGE_NAME}:${{ inputs.image_tag }}" >> "$GITHUB_OUTPUT"
      shell: bash
