name: Deploy to DEV

on:
  push:
    branches:
      - main
  pull_request:
    # From docs: if no activity types are specified, the workflow runs when a pull request is opened or reopened or when the head branch of the pull request is updated.
    paths:
      - "deploy/**"
      - ".github/**"
      - "src/**"
      - "tests/**"
      - "Dockerfile"
      - "yarn.lock"
  workflow_dispatch:
    inputs:
      environment:
        description: "Github deployment environment"
        required: false
        default: "dev"
        type: choice
        options:
          - dev

jobs:
  # snyk:
  #   name: Snyk Security Scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

  #     - name: Build local Docker image
  #       working-directory: ${{ github.workspace }}
  #       run: |
  #         docker build -t laa-civil-manage-api ./
  #         docker save laa-civil-manage-api -o image.tar

  #     - name: Run Snyk to scan Docker image from tarball
  #       uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
  #       with:
  #         image: image.tar
  #         args: --docker --severity-threshold=high
  #           --file=Dockerfile --policy-path=.snyk
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build and Publish Action
        uses: ./.github/actions/build_and_test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

      - name: Set up AWS credentials for ECR and Kubernetes
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        id: login-ecr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push image with local action
        uses: ./.github/actions/docker_build_and_push
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ vars.ECR_REPOSITORY }}
          dockerfile_path: Dockerfile
          image_tag: ${{ github.sha }}

  # unit-tests:
  #   name: Unit Tests
  #   uses: ./.github/workflows/unit-tests.yml
  #   needs:
  #     - build-image
  #   # Only run tests when deploying to dev
  #   if: success() && (github.event_name != 'workflow_dispatch' ||
  #     (github.event_name == 'workflow_dispatch' &&
  #     github.event.inputs.environment == 'dev' ||
  #     github.event.inputs.environment == null))

  # playwright:
  #   name: Playwright Tests
  #   uses: ./.github/workflows/playwright.yml
  #   needs:
  #     - build-image
  #   # Only run tests when deploying to dev
  #   if: success() && (github.event_name != 'workflow_dispatch' ||
  #     (github.event_name == 'workflow_dispatch' &&
  #     github.event.inputs.environment == 'dev' ||
  #     github.event.inputs.environment == null))

  # zap-scan:
  #   name: ZAP Security Scanning
  #   uses: ./.github/workflows/zap-scanning.yml
  #   needs:
  #     - build-image
  #   # Only run tests when deploying to dev
  #   if: success() && (github.event_name != 'workflow_dispatch' ||
  #     (github.event_name == 'workflow_dispatch' &&
  #     github.event.inputs.environment == 'dev' ||
  #     github.event.inputs.environment == null))

  deploy-dev:
    if: ${{ github.actor != 'dependabot[bot]' }}
    environment: dev
    runs-on: ubuntu-latest
    needs:
      # - snyk
      - build-docker-image
      # - unit-tests
      # - playwright
      # - zap-scan

    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2

      - name: Deploy to dev
        uses: ./.github/actions/deploy
        with:
          app-environment: dev
          auth_client_id: ${{ secrets.AUTH_CLIENT_ID }}
          auth_client_secret: ${{ secrets.AUTH_CLIENT_SECRET }}
          auth_directory_url: ${{ secrets.AUTH_DIRECTORY_URL }}
          auth_redirect_url: ${{ secrets.AUTH_REDIRECT_URL }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          ratelimit_max: ${{ vars.RATE_LIMIT_MAX }}
          ratewindow_ms: ${{ vars.RATE_WINDOW_MS }}
          service_name: ${{ vars.SERVICE_NAME }}
          session_name: ${{ vars.SESSION_NAME }}
          session_secret: ${{ secrets.SESSION_SECRET }}

#   notify-slack:
#     # environment: dev
#     needs: deploy-dev
#     runs-on: ubuntu-latest
#     if: always() && github.ref_name == 'main'
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6.0.2
#       - name: Send Slack Notification
#         uses: ./.github/actions/notify
#         with:
#           app-environment: dev
#           slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
#           pipeline_status: "${{ job.status }} ${{ join(needs.*.result, ' ') }}"
